version: '3'
services:
  kafka:
    ports:
      - 2181:2181
      - 3030:3030
      - 8081:8081
      - 8082:8082
      - 8083:8083
      - 9092:9092
      - 9581-9585:9581-9585
    image: landoop/fast-data-dev
    environment: 
    - ADV_HOST=192.168.202.99
    volumes:
      - ./data:/data